management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 9080
  servlet:
    context-path: /api/flights/provider/beta
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain    

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10
    
connector:
   catalog:
      host: localhost:6080
      responseTimeout: 1000
      connectionTimeout: 1000
      readTimeout: 1000