management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 9080
  servlet:
    context-path: /api/flights/provider/beta

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10
    
connector:
   catalog:
      host: api-catalog-cache:80
      responseTimeout: 1000
      connectionTimeout: 1000
      readTimeout: 1000
cache:
  configuration:
    CATALOG_CITY:
       refreshAfterWriteTime: 5 #MINUTES
       expireAfterWriteTime: 10 #MINUTES
       maxSize: 180