management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 4080
  servlet:
    context-path: /api/flights/clusters

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10
    
connector:
   catalog:
      host: api-catalog-cache:80
      responseTimeout: 2000
      connectionTimeout: 2000
      readTimeout: 2000
   pricing:
      host: api-pricing:5080
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000   
   itineraries-search:
      host: api-itineraries-search:7080
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000   
cache:
  configuration:
    CATALOG_CITY:
       refreshAfterWriteTime: 5 #MINUTES
       expireAfterWriteTime: 10 #MINUTES
       maxSize: 180      