management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 4080
  servlet:
    context-path: /api/flights/clusters
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain    
    
jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10
    
redis:
   host: api-clusters-db
   port: 6379    
    
connector:
   catalog:
      host: api-catalog:6080
      responseTimeout: 2000
      connectionTimeout: 2000
      readTimeout: 2000
   pricing:
      host: api-pricing:5080
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000   
   itineraries-search:
      host: api-itineraries-search:7080
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000         