management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 6080
  servlet:
    context-path: /api/flights/catalog
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain     

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

spring:
  flyway:
    locations: classpath:db/migration
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  datasource:
    url: "jdbc:mysql://localhost:3310/flights_catalog?autoReconnect=true"
    username: root
    password: muppet
    driverClassName: com.mysql.cj.jdbc.Driver
    validation-query: select 1;
    maxActive: 100
  jpa:
    show-sql: false
    generate-ddl: false    
    properties:    
      hibernate:
        ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy                
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl.auto: validate